[package]
name = "metadata-server"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.11+spec-1.1.0"
anyhow = "1.0.100"
thiserror = "2.0.17"
log4rs = "1.4.0-rc2"
log = "0.4.29"